name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller pandas opencv-python-headless pymupdf reportlab pyzbar

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed --name "AMC_Exam_Suite" --collect-all pyzbar --hidden-import reportlab.graphics.barcode.code128 --hidden-import reportlab.graphics.barcode.code93 --hidden-import reportlab.graphics.barcode.code39 --hidden-import reportlab.graphics.barcode.usps --hidden-import reportlab.graphics.barcode.usps4s --hidden-import reportlab.graphics.barcode.ecc200 --hidden-import reportlab.graphics.barcode.ecc200datamatrix --hidden-import reportlab.graphics.barcode.qr --hidden-import reportlab.graphics.barcode.qrencoder --hidden-import reportlab.graphics.barcode.lto AMC_Exam_Suite.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AMC_Exam_Suite_Windows_App
        path: dist/AMC_Exam_Suite.exe
